# Generated by Django 4.1.5 on 2023-01-24 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blurb", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="quesmodel",
            name="quiz",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.quizmodel",
            ),
        ),
    ]
