# Generated by Django 4.1.5 on 2023-01-24 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_quizmodel_quesmodel_quiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quesmodel",
            name="quiz",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="quiz.quizmodel",
            ),
        ),
    ]
