# Generated by Django 4.1.5 on 2023-01-30 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0005_quizmodel_quiz_type_quizmodel_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizmodel",
            name="creator",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="persmodel",
            name="ans3",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ans3",
                to="quiz.personality",
            ),
        ),
        migrations.AlterField(
            model_name="persmodel",
            name="ans4",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ans4",
                to="quiz.personality",
            ),
        ),
        migrations.AlterField(
            model_name="persmodel",
            name="op3",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="persmodel",
            name="op4",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="quesmodel",
            name="op3",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="quesmodel",
            name="op4",
            field=models.CharField(blank=True, default="", max_length=200, null=True),
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fullname", models.CharField(max_length=50, verbose_name="Full Name")),
                ("birthdate", models.DateTimeField(verbose_name="Birthday")),
                ("url", models.URLField(blank=True, verbose_name="Website")),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        upload_to="img/users/profile",
                        verbose_name="Picture/Avatar",
                    ),
                ),
                ("bio", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        default="1",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
