# Generated by Django 4.1.5 on 2023-01-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_quizmodel_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizmodel",
            name="cover",
            field=models.ImageField(
                blank=True, default="", null=True, upload_to="images/"
            ),
        ),
    ]
