# Generated by Django 4.1.5 on 2023-09-05 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0013_alter_persmodel_ans1_alter_persmodel_ans2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quesmodel",
            name="ans",
            field=models.CharField(
                choices=[
                    ("option1", "op1"),
                    ("option2", "op2"),
                    ("option3", "op3"),
                    ("option4", "op4"),
                ],
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="quizmodel",
            name="cover",
            field=models.ImageField(
                blank=True,
                default="static/quiz-photo.jpeg",
                null=True,
                upload_to="static/",
            ),
        ),
    ]
